### ISSUE TITLE
Missing texture in format 12(mcver: 1.19.3)

### ISSUE THREAD

**Issue by tsutoringo** [freeserverproject/texture#113]
[Java Edition 1.19.3 - Minecraft Wiki](https://minecraft.fandom.com/ja/wiki/Java_Edition_1.19.3#:~:text=%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E3%81%A7%E3%81%AF%E3%80%81%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AAtextures/item%E3%81%BE%E3%81%9F%E3%81%AFtextures/block%E3%81%AB%E5%AD%98%E5%9C%A8%E3%81%97%E3%81%AA%E3%81%84%E3%83%86%E3%82%AF%E3%82%B9%E3%83%81%E3%83%A3%E3%81%AF%E8%87%AA%E5%8B%95%E7%9A%84%E3%81%AB%E3%81%AF%E8%AA%8D%E8%AD%98%E3%81%95%E3%82%8C%E3%81%AA%E3%81%8F%E3%81%AA%E3%82%8A%E3%80%81%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF%E3%81%AB%E5%A4%B1%E6%95%97%E3%81%99%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E3%80%82)

**Comment by tererun** [comment]
texture以下のパスの探し方が変わったらしい　つとが対応中

**Comment by graycat27** [comment]
![image](https://user-images.githubusercontent.com/64903817/213606468-0ff0cd80-6e83-406a-bd55-37b33dfb3b8e.png)
![image](https://user-images.githubusercontent.com/64903817/213606596-71743d9f-378a-4846-a4c7-69174a899cce.png)
1.19.3世界に入ったらこの状況だったのでissue立てようかと思ったら、立ってた

**Comment by graycat27** [comment]
@tsutoringo 1.19ブランチでテクスチャパック作って手動DL&適用できるようにしてもらえるとたすかりますです
ご検討ください

**Comment by Alpha9n** [comment]
おそらく1.19.3テクスチャは後方互換性は確保されてると思うので別にて用意は必要ないと考えています。

**Comment by graycat27** [comment]
あ～～、既定フォルダ以外からは自動で読み込まなくなったからメタで補ってあげる必要があるだけで、過去バージョンで読み込めなくなるような変更ではないのか

**Comment by Alpha9n** [comment]
そうです

**Comment by graycat27** [comment]
@tsutoringo 麦わら帽子だけおかしいみたいです
![image](https://user-images.githubusercontent.com/64903817/217244406-54a16300-9d88-4b8a-a549-152f523be231.png)
![image](https://user-images.githubusercontent.com/64903817/217244453-142d1765-f085-4804-ae75-57d3d69d5692.png)

**Comment by tsutoringo** [comment]
🥺
