### ISSUE TITLE
魚のテクスチャ

### ISSUE THREAD

**Issue by tsutoringo** [freeserverproject/texture#12]
未だに追加されてない魚のテクスチャのtodo置いときますね

テクスチャ作成
- [x] ~~アジ~~
- [x] ~~ハリセンボン~~
- [x] ~~ミノカサゴ~~
- [x] ~~ナポレオンフィッシュ~~
- [x] ~~チョウチョウオ~~
- [x] ~~ナンヨウハギ~~
- [x] ~~クマノミ~~
- [x] ~~タツノオトシゴ~~
- [x] ~~クリオネ~~
- [x] ~~チョウザメ~~
- [x] ~~エンドリケリー~~
- [x] ~~ピラルクー~~
- [x] ~~ガー~~
- [x] ~~ドラド~~
- [x] ~~アロワナ~~
- [x] ~~ピラニア~~
- [x] ~~レインボーフィッシュ~~
- [x] ~~ネオンテトラ~~
- [x] ~~ベタ~~
- [x] ~~エンゼルフィッシュ~~
- [x] ~~ドクターフィッシュ~~
- [x] ~~グッピー~~
- [x] ~~シャンハイガニ~~

モデル作成
- [x] アジ
- [x] ミノカサゴ
- [x] ハリセンボン
- [x] ナポレオンフィッシュ
- [x] チョウチョウオ
- [x] ナンヨウハギ
- [x] クマノミ
- [x] タツノオトシゴ
- [x] クリオネ
- [x] チョウザメ
- [x] エンドリケリー
- [x] ピラルクー
- [x] ガー
- [x] ドラド
- [x] アロワナ
- [x] ピラニア
- [x] レインボーフィッシュ
- [x] ネオンテトラ
- [x] ベタ
- [x] エンゼルフィッシュ
- [x] ドクターフィッシュ
- [x] グッピー
- [x] シャンハイガニ

**Comment by Alpha9n** [comment]
2021/02/14 AM6:37
現在編集中

**Comment by graycat27** [comment]
ぬち、一気制作よくがんばりました◎

**Comment by Nakatai-0322** [comment]
ご苦労さまでした！
