### ISSUE TITLE
フィギュアの頭のテクスチャが反転してる

### ISSUE THREAD

**Issue by tsutoringo** [freeserverproject/texture#36]
フィギュアのモデルの指定が間違ってるので直してください

**Comment by tsutoringo** [comment]
![image](https://user-images.githubusercontent.com/33830878/108702016-08c49f80-754c-11eb-837f-e71ecf95a9e4.png)

**Comment by tsutoringo** [comment]
正しくは
![image](https://user-images.githubusercontent.com/33830878/108702139-30b40300-754c-11eb-9bc4-fde463ca2457.png)

**Comment by graycat27** [comment]
フィギュアの頭部、天面のテクスチャの向きが違う。
テクスチャが、本来の方向と前後逆になった状態でフィギュアに貼り付けられている。
